language: php
php:
  - 5.4
  - 5.5

branches:
    only:
        - master

before_install:
    - mysql -uroot -h localhost -e "USE mysql; UPDATE user SET password=PASSWORD('topsecret') WHERE user='root'; FLUSH PRIVILEGES;"

install:
    - ./install.sh

script:
    - vendor/bin/phpunit tests/SimpleProductHandlerTest.php
    - vendor/bin/phpunit tests/ConfigurableProductHandlerTest.php

notifications:
  flowdock:
    secure: a99965ce11998f1e3796bb00ddb0dedd