language: php
php:
  - 5.4
  - 5.5

branches:
    only:
        - master

install:
    - ./install.sh

script:
    - vendor/bin/phpunit

notifications:
  flowdock:
    secure: a99965ce11998f1e3796bb00ddb0dedd